# Generated by Django 3.0.8 on 2020-08-12 12:26

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200812_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null='user10461', unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='WPCouple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protectee', to=settings.AUTH_USER_MODEL)),
                ('wearer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
